import path from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "@playwright/test";

// The Playwright harness every later e2e step reuses (PLAN §10). This step defines the two canonical
// projects `web` and `desktop`; S7.4 adds `web-realtime`, S11.1 adds `web-worker`. No step ever uses
// a `web-chromium` project — that name does not exist.

const here = path.dirname(fileURLToPath(import.meta.url));

// Frozen target URLs (§10). WEB_URL is the PR target (app served by the Vite dev server, which
// proxies /api → the e2e worker on 8787). WORKER_URL is the worker-served parity target that S11.1
// flips a suite to; for that target the harness rebuilds the app BEFORE wrangler starts and restarts
// wrangler after any rebuild — never hot reload (§14). REALTIME_URL is S7.4's @realtime target: the
// real-SFU worker on 8788 serves the built app (assets binding) AND /api same-origin, so the browser's
// real WebRTC calls reach the real Cloudflare Realtime SFU (the Vite proxy is pinned to 8787).
export const WEB_URL = "http://localhost:5173";
export const WORKER_URL = "http://localhost:8787";
export const REALTIME_URL = "http://localhost:8788";

// Committed fake-media fixture (regenerated by scripts/gen-fixtures.mjs). Passed to Chromium as an
// absolute path so the fake audio device emits the 440 Hz tone instead of the default beep.
export const TONE_WAV = path.join(here, "fixtures", "tone-440hz-10s.wav");

// The fake-media Chromium switches used by every browser project (real capture stack via the branded
// channel; the tone WAV drives the local analyser past the §App-B speaking threshold).
const fakeMediaArgs = [
  "--use-fake-ui-for-media-stream",
  "--use-fake-device-for-media-stream",
  `--use-file-for-fake-audio-capture=${TONE_WAV}`,
  // Chromium 150 runs the audio service out-of-process, and the fake-capture file switch never
  // reaches it — the fake mic emits SILENCE (first seen on the desktop harness, S7.4; resurfaced
  // as audioLevel=0 in the nightly @realtime voice suite on ubuntu runners while bytesReceived
  // kept climbing). Forcing in-process audio makes the tone actually play.
  "--disable-features=AudioServiceOutOfProcess",
];

// webServer entries. The app dev server + the e2e worker (mock SFU, --env e2e picks .dev.vars.e2e)
// always run; the real-SFU worker (8788, default env → real .dev.vars, no TAVERN_SFU_MOCK) is
// appended ONLY when REALTIME_APP_ID is present (Playwright has no per-project webServer).
const appServer = {
  command: "pnpm -F @tavern/app dev",
  url: WEB_URL,
  reuseExistingServer: !process.env.CI,
  timeout: 120_000,
};
const e2eWorker = {
  command: "pnpm -F @tavern/worker exec wrangler dev --env e2e --port 8787",
  url: `${WORKER_URL}/api/health`,
  reuseExistingServer: !process.env.CI,
  timeout: 120_000,
};
const realtimeWorker = {
  command: "pnpm -F @tavern/worker exec wrangler dev --port 8788",
  url: `${REALTIME_URL}/api/health`,
  reuseExistingServer: !process.env.CI,
  timeout: 120_000,
};

export default defineConfig({
  testDir: here,
  // §14: retry>1 is a bug to fix, not a knob. Serial + single worker because the whole run shares one
  // wrangler dev process (and its D1/DO state).
  retries: process.env.CI ? 1 : 0,
  fullyParallel: false,
  workers: 1,
  reporter: [["list"], ["html", { open: "never" }]],
  projects: [
    {
      name: "web",
      testMatch: "web/**",
      // The @realtime specs need the real SFU (remote-media getStats) — they run ONLY in web-realtime.
      grepInvert: /@realtime/,
      use: {
        // MANDATORY: the headless shell has no media-capture stack (§10) — the branded "chromium"
        // channel is the full Chrome-for-Testing build, which does.
        channel: "chromium",
        baseURL: WEB_URL,
        permissions: ["microphone", "camera"],
        launchOptions: { args: fakeMediaArgs },
      },
    },
    {
      // §10 hermeticity split: the @realtime nightly suite against the REAL Cloudflare Realtime SFU.
      // Same testDir; only the @realtime-tagged tests run. baseURL is the real-SFU worker on 8788,
      // which serves the built app AND /api same-origin (so the browser's WebRTC reaches the real SFU).
      name: "web-realtime",
      testMatch: "web/**",
      grep: /@realtime/,
      use: {
        channel: "chromium",
        baseURL: REALTIME_URL,
        permissions: ["microphone", "camera"],
        launchOptions: { args: fakeMediaArgs },
      },
    },
    {
      // Electron smoke — no browser fixtures; specs drive `_electron.launch` through the harness.
      name: "desktop",
      testMatch: "desktop/**",
    },
  ],
  webServer: [appServer, e2eWorker, ...(process.env.REALTIME_APP_ID ? [realtimeWorker] : [])],
});
