import path from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "@playwright/test";

// The Playwright harness every later e2e step reuses (PLAN §10). This step defines the two canonical
// projects `web` and `desktop`; S7.4 adds `web-realtime`, S11.1 adds `web-worker`. No step ever uses
// a `web-chromium` project — that name does not exist.

const here = path.dirname(fileURLToPath(import.meta.url));

// Frozen target URLs (§10). WEB_URL is the PR target (app served by the Vite dev server, which
// proxies /api → the worker). WORKER_URL is the worker-served parity target that S11.1 flips a suite
// to; for that target the harness rebuilds the app BEFORE wrangler starts and restarts wrangler after
// any rebuild — never hot reload (§14).
export const WEB_URL = "http://localhost:5173";
export const WORKER_URL = "http://localhost:8787";

// Committed fake-media fixture (regenerated by scripts/gen-fixtures.mjs). Passed to Chromium as an
// absolute path so the fake audio device emits the 440 Hz tone instead of the default beep.
export const TONE_WAV = path.join(here, "fixtures", "tone-440hz-10s.wav");

export default defineConfig({
  testDir: here,
  // §14: retry>1 is a bug to fix, not a knob. Serial + single worker because the whole run shares one
  // wrangler dev process (and its D1/DO state).
  retries: process.env.CI ? 1 : 0,
  fullyParallel: false,
  workers: 1,
  reporter: [["list"], ["html", { open: "never" }]],
  projects: [
    {
      name: "web",
      testMatch: "web/**",
      use: {
        // MANDATORY: the headless shell has no media-capture stack (§10) — the branded "chromium"
        // channel is the full Chrome-for-Testing build, which does.
        channel: "chromium",
        baseURL: WEB_URL,
        permissions: ["microphone", "camera"],
        launchOptions: {
          args: [
            "--use-fake-ui-for-media-stream",
            "--use-fake-device-for-media-stream",
            `--use-file-for-fake-audio-capture=${TONE_WAV}`,
          ],
        },
      },
    },
    {
      // Electron smoke — no browser fixtures; specs drive `_electron.launch` through the harness.
      name: "desktop",
      testMatch: "desktop/**",
    },
  ],
  webServer: [
    {
      command: "pnpm -F @tavern/worker dev",
      url: "http://localhost:8787/api/health",
      reuseExistingServer: !process.env.CI,
      timeout: 120_000,
    },
    {
      command: "pnpm -F @tavern/app dev",
      url: "http://localhost:5173",
      reuseExistingServer: !process.env.CI,
      timeout: 120_000,
    },
  ],
});
