// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ChatMsg = { id: number, channelId: string, userId: string, content: string, nonce: string | null, createdAt: number, };
