// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrackInfo = { ownerId: string, trackName: string, 
/**
 * "mic" | "screen" | "webcam"
 */
kind: string, simulcast: boolean, width: number, height: number, fps: number, };
