// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClientFrame = { "t": "chat.send", channelId: string, content: string, nonce: string, } | { "t": "chat.history", channelId: string, beforeId: number | null, limit: number, } | { "t": "voice.join", channelId: string, } | { "t": "voice.leave", } | { "t": "heartbeat", };
