// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Budget } from "./Budget";
import type { ChatMsg } from "./ChatMsg";
import type { Member } from "./Member";
import type { Presence } from "./Presence";
import type { TrackInfo } from "./TrackInfo";

export type ServerFrame = { "t": "hello.ok", userId: string, roster: Array<Member>, presence: Array<Presence>, tracks: Array<TrackInfo>, budget: Budget, } | { "t": "heartbeat.ok", } | { "t": "error", code: string, msg: string, } | { "t": "chat.msg", id: number, channelId: string, userId: string, content: string, nonce: string | null, createdAt: number, } | { "t": "chat.history", channelId: string, messages: Array<ChatMsg>, hasMore: boolean, } | { "t": "presence", userId: string, state: string, channelId: string | null, } | { "t": "profile", userId: string, nickname: string, color: string, avatarKey: string | null, } | { "t": "tracks", ownerId: string, tracks: Array<TrackInfo>, } | { "t": "budget", level: string, estMbps: number, monthGb: number, };
